-- STABILITY BANK 3.0 — ADMIN RUNTIME FIX
-- Run this file once in Supabase SQL Editor.

create or replace function public.admin_balance_operation(p_amount numeric,p_description text,p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare old_balance numeric; new_balance numeric; a numeric:=coalesce(p_amount,0);
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if a=0 then raise exception 'Сумма не может быть нулевой'; end if;
 select coalesce(balance,0) into old_balance from public.profiles where id=p_player_id for update;
 if not found then raise exception 'Игрок не найден'; end if;
 if lower(coalesce((select status from public.profiles where id=p_player_id),'active'))<>'active' then raise exception 'Игрок не активен'; end if;
 new_balance:=old_balance+a;
 if new_balance<0 then raise exception 'Недостаточно средств у игрока'; end if;
 update public.profiles set balance=new_balance where id=p_player_id;
 insert into public.transactions(from_user,to_user,amount,type,description,created_at)
 values(case when a<0 then p_player_id else auth.uid() end,case when a>0 then p_player_id else auth.uid() end,abs(a),case when a>0 then 'deposit' else 'withdraw' end,coalesce(nullif(trim(p_description),''),'Административная операция'),now());
 return jsonb_build_object('success',true,'old_balance',old_balance,'new_balance',new_balance);
end;$$;
grant execute on function public.admin_balance_operation(numeric,text,uuid) to authenticated;

create or replace function public.admin_issue_penalty(p_amount numeric,p_player_id uuid,p_reason text,p_title text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare fid uuid;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'Сумма штрафа должна быть больше нуля'; end if;
 if not exists(select 1 from public.profiles where id=p_player_id and lower(coalesce(status,'active'))='active') then raise exception 'Игрок не найден или не активен'; end if;
 insert into public.fines(user_id,amount,reason,title,is_paid,created_at)
 values(p_player_id,p_amount,coalesce(nullif(trim(p_reason),''),'Штраф'),coalesce(nullif(trim(p_title),''),'Штраф'),false,now()) returning id into fid;
 return jsonb_build_object('success',true,'fine_id',fid);
end;$$;
grant execute on function public.admin_issue_penalty(numeric,uuid,text,text) to authenticated;

create or replace function public.admin_cancel_fine(p_fine_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare f public.fines%rowtype;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 select * into f from public.fines where id=p_fine_id for update;
 if not found then raise exception 'Штраф не найден'; end if;
 if f.is_paid then raise exception 'Штраф уже оплачен'; end if;
 update public.fines set is_paid=true where id=p_fine_id;
 insert into public.transactions(from_user,to_user,amount,type,description,created_at)
 values(auth.uid(),f.user_id,f.amount,'fine_cancel','Отмена штрафа #'||p_fine_id,now());
 return jsonb_build_object('success',true,'fine_id',p_fine_id);
end;$$;
grant execute on function public.admin_cancel_fine(uuid) to authenticated;

create or replace function public.issue_credit(p_user_id uuid,p_amount numeric,p_interest numeric default 0)
returns jsonb language plpgsql security definer set search_path=public as $$
declare cid bigint;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'Сумма кредита должна быть больше нуля'; end if;
 if not exists(select 1 from public.profiles where id=p_user_id and lower(coalesce(status,'active'))='active') then raise exception 'Игрок не найден или не активен'; end if;
 insert into public.credits(user_id,amount,remaining,interest_rate,is_closed,created_at)
 values(p_user_id,p_amount,p_amount,coalesce(p_interest,0),false,now()) returning id into cid;
 update public.profiles set balance=coalesce(balance,0)+p_amount where id=p_user_id;
 insert into public.transactions(from_user,to_user,amount,type,description,created_at)
 values(auth.uid(),p_user_id,p_amount,'credit','Выдача кредита #'||cid,now());
 return jsonb_build_object('success',true,'credit_id',cid,'amount',p_amount);
end;$$;
grant execute on function public.issue_credit(uuid,numeric,numeric) to authenticated;

create table if not exists public.bank_notifications(
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 title text not null,message text not null,kind text not null default 'info',is_read boolean not null default false,created_at timestamptz not null default now()
);
alter table public.bank_notifications enable row level security;
drop policy if exists "players read own bank notifications" on public.bank_notifications;
create policy "players read own bank notifications" on public.bank_notifications for select to authenticated using(user_id=auth.uid());
create or replace function public.bank_create_notification(p_user_id uuid,p_title text,p_message text,p_kind text default 'info')
returns jsonb language plpgsql security definer set search_path=public as $$
declare nid bigint;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if not exists(select 1 from public.profiles where id=p_user_id) then raise exception 'Игрок не найден'; end if;
 insert into public.bank_notifications(user_id,title,message,kind,created_at) values(p_user_id,coalesce(nullif(trim(p_title),''),'Сообщение банка'),coalesce(nullif(trim(p_message),''),'Без текста'),coalesce(nullif(trim(p_kind),''),'info'),now()) returning id into nid;
 return jsonb_build_object('success',true,'id',nid);
end;$$;
grant execute on function public.bank_create_notification(uuid,text,text,text) to authenticated;

notify pgrst,'reload schema';
