import { supabase } from './supabase-client.js';
function err(e){ return new Error(e?.message || e?.details || e?.hint || 'Ошибка серверной операции'); }
async function rpc(name, params){ const {data,error}=await supabase.rpc(name,params); if(error)throw err(error); return data; }
export async function getAllPlayers(){ const {data,error}=await supabase.from('profiles').select('*').eq('role','player').order('created_at',{ascending:false}); if(error)throw error; return data||[]; }
export async function updatePlayerProfile(id,u){ return rpc('admin_update_player_profile',{p_player_id:id,p_full_name:u.full_name||'',p_birth_date:u.birth_date||null,p_passport_number:u.passport_number||'',p_username:u.username||''}); }
function amount(v){const n=Number(String(v??'').replace(',','.'));if(!Number.isFinite(n)||n<=0)throw Error('Введите корректную сумму');return n;}
export async function depositFunds(id,value,description='Пополнение администратором'){return rpc('admin_balance_operation',{p_amount:amount(value),p_description:description||'Пополнение администратором',p_player_id:id});}
export async function withdrawFunds(id,value,description='Снятие администратором'){return rpc('admin_balance_operation',{p_amount:-amount(value),p_description:description||'Снятие администратором',p_player_id:id});}
export async function issueFine(id,value,reason){const n=amount(value);return rpc('admin_issue_penalty',{p_amount:n,p_player_id:id,p_reason:reason||'Штраф',p_title:reason||'Штраф'});}
export async function issueCredit(id,value,interest=0){return rpc('issue_credit',{p_user_id:id,p_amount:amount(value),p_interest:Number(interest)||0});}
export async function getUserFines(id){const {data,error}=await supabase.from('fines').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getUserCredits(id){const {data,error}=await supabase.from('credits').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getTransactions(id=null){let q=supabase.from('transactions').select('*').order('created_at',{ascending:false}).limit(500);if(id)q=q.or(`from_user.eq.${id},to_user.eq.${id}`);const {data,error}=await q;if(error)throw error;return data||[];}
export async function deleteTransaction(id){return rpc('admin_delete_transaction',{p_transaction_id:String(id)});}
export async function clearPlayerHistory(id){return rpc('admin_clear_player_history',{p_player_id:id});}
export async function sendNotification(id,title,message,kind='info'){if(!String(message||'').trim())throw Error('Введите текст уведомления');return rpc('bank_create_notification',{p_user_id:id,p_title:title||'Сообщение банка',p_message:message,p_kind:kind});}
export async function markNotificationRead(id){return rpc('mark_bank_notification_read',{p_notification_id:id});}
export async function paySalary(id,job,params={}){const amount=calculateSalary(job,params);if(amount<=0)throw Error('Не удалось рассчитать зарплату');const j=SALARY_JOBS[job];return rpc('admin_issue_salary',{p_player_id:id,p_job_key:job,p_job_title:j?.[1]||job,p_amount:amount,p_units:Number(params.orders||1),p_parameters:params});}
export const SALARY_JOBS={mine:['Обычные работы','🦺 Шахта','fixed',300],courier:['Обычные работы','🛵 Курьер','orders',80,9],mail:['Обычные работы','📪 Почта','fixed',1000],taxi:['Обычные работы','🚕 Такси','taxi',180,7],bus:['Обычные работы','🚌 Автобус','bus',1600],garbage:['Обычные работы','🚮 Мусоровоз','fixed',2700],delivery:['Обычные работы','🚚 Развозчик','delivery',1400],trucker:['Обычные работы','🚛 Дальнобойщик','contract',0],ess_driver:['ЕСС','🚒 Водитель','fixed',1500],ess_firefighter:['ЕСС','🚒 Пожарный','fixed',1800],ess_rescuer:['ЕСС','🚒 Спасатель','fixed',2200],ess_inspector:['ЕСС','🚒 Инспектор','fixed',2500],ess_paramedic:['ЕСС','🚒 Фельдшер','fixed',2800],ess_doctor:['ЕСС','🚒 Врач','fixed',3200],ess_narcologist:['ЕСС','🚒 Нарколог','fixed',3600],ess_surgeon:['ЕСС','🚒 Хирург','fixed',4000],mvd_private:['МВД','🚓 Рядовой','fixed',1500],mvd_junior_sergeant:['МВД','🚓 Мл. сержант','fixed',1800],mvd_sergeant:['МВД','🚓 Сержант','fixed',2100],mvd_master_sergeant:['МВД','🚓 Старшина','fixed',2400],mvd_warrant:['МВД','🚓 Прапорщик','fixed',2700],mvd_junior_lieutenant:['МВД','🚓 Мл. лейтенант','fixed',3000],mvd_lieutenant:['МВД','🚓 Лейтенант','fixed',3300],mvd_captain:['МВД','🚓 Капитан','fixed',3600],mvd_major:['МВД','🚓 Майор','fixed',3900],mvd_lieutenant_colonel:['МВД','🚓 Подполковник','fixed',4200],mil_private:['Воинская часть','🪖 Рядовой','fixed',500],mil_corporal:['Воинская часть','🪖 Ефрейтор','fixed',800],mil_junior_sergeant:['Воинская часть','🪖 Мл. сержант','fixed',1100],mil_sergeant:['Воинская часть','🪖 Сержант','fixed',2000],mil_senior_sergeant:['Воинская часть','🪖 Ст. сержант','fixed',2300],mil_master_sergeant:['Воинская часть','🪖 Старшина','fixed',2600],mil_warrant:['Воинская часть','🪖 Прапорщик','fixed',2900],mil_junior_lieutenant:['Воинская часть','🪖 Мл. лейтенант','fixed',3200],mil_lieutenant:['Воинская часть','🪖 Лейтенант','fixed',3500]};
export function calculateSalary(job,p={}){const j=SALARY_JOBS[job];if(!j)return 0;const t=j[2];if(t==='fixed')return j[3];if(t==='orders')return Math.min(j[4],Math.max(0,Number(p.orders||0)))*j[3];if(t==='contract')return Math.max(0,Number(p.contract_amount||0));if(t==='taxi'){const n=Math.min(7,Math.max(0,Number(p.orders||0)));return Math.round(n*180+({low:0,medium:300,high:600,business:1200}[p.vehicle_class]??0));}if(t==='bus')return Math.round(1600*({none:1,vip_interior:1.3,soundproof:1.4,climate_monitors:1.5}[p.tuning]??1));if(t==='delivery')return Math.round(1400*({none:1,trunk:1.2,air_suspension:1.5}[p.tuning]??1));return 0;}
let modal=null;
export function closeAdminModal(){document.querySelectorAll('.modal').forEach(m=>{m.classList.remove('open');m.style.display='none';m.setAttribute('aria-hidden','true');});document.body.classList.remove('modal-open');modal=null;}
window.closeAdminModal=closeAdminModal;
document.addEventListener('click',e=>{const close=e.target.closest('#close,.modal-close,[data-close-modal]');if(close){e.preventDefault();e.stopImmediatePropagation();closeAdminModal();return;}if(e.target.classList.contains('modal')){e.preventDefault();closeAdminModal();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAdminModal();});
export function openAdminModal(id){const m=document.getElementById(id);if(!m)return false;closeAdminModal();m.style.display='flex';m.classList.add('open');m.setAttribute('aria-hidden','false');modal=m;return true;}
window.openAdminModal=openAdminModal;
