import { supabase } from './supabase-client.js';
const fail=e=>new Error(e?.message||e?.details||e?.hint||'Ошибка Supabase');
const rpc=async(n,p)=>{const{data,error}=await supabase.rpc(n,p);if(error)throw fail(error);return data};
const num=v=>{const n=Number(String(v??'').replace(',','.'));if(!Number.isFinite(n)||n<=0)throw Error('Введите корректную сумму');return n};
const notice=async(id,title,message,kind='info')=>{if(!id||!String(message||'').trim())return;const{error}=await supabase.rpc('bank_create_notification',{p_user_id:id,p_title:title,p_message:message,p_kind:kind});if(error)throw fail(error)};
export async function getAllPlayers(){const{data,error}=await supabase.from('profiles').select('*').eq('role','player').order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function updatePlayerProfile(id,u){return rpc('admin_update_player_profile',{p_player_id:id,p_full_name:u.full_name||'',p_birth_date:u.birth_date||null,p_passport_number:u.passport_number||''})}
export async function depositFunds(id,v,d){const a=num(v);const r=await rpc('admin_balance_operation',{p_amount:a,p_description:d||'Пополнение администратором',p_player_id:id});await notice(id,'Пополнение счёта',`Ваш банковский счёт пополнен на ${a.toLocaleString('ru-RU')} ₽. ${d||''}`,'success');return r}
export async function withdrawFunds(id,v,d){const a=num(v);const r=await rpc('admin_balance_operation',{p_amount:-a,p_description:d||'Снятие администратором',p_player_id:id});await notice(id,'Списание средств',`С вашего банковского счёта списано ${a.toLocaleString('ru-RU')} ₽. ${d||''}`,'warning');return r}
export async function issueFine(id,v,r){const a=num(v),reason=String(r||'Штраф');return rpc('admin_issue_penalty',{p_amount:a,p_player_id:id,p_reason:reason,p_title:'Вам выписан штраф'})}
export async function issueCredit(id,v,i=0){const a=num(v),rate=Number(i)||0;return rpc('admin_issue_credit',{p_player_id:id,p_amount:a,p_interest:rate})}
export const sendNotification=(id,title,message,kind='info')=>notice(id,title||'Сообщение банка',message,kind);
export const markNotificationRead=id=>rpc('mark_bank_notification_read',{p_notification_id:id});
export const deleteTransaction=id=>rpc('admin_delete_transaction',{p_transaction_id:String(id)});
export const clearPlayerHistory=id=>rpc('admin_clear_player_history',{p_player_id:id});
export async function getUserFines(id){const{data,error}=await supabase.from('fines').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getUserCredits(id){const{data,error}=await supabase.from('credits').select('*').eq('user_id',id).order('created_at',{ascending:false});if(error)throw error;return data||[]}
export async function getTransactions(id=null){let q=supabase.from('transactions').select('*').order('created_at',{ascending:false}).limit(500);if(id)q=q.or(`from_user.eq.${id},to_user.eq.${id}`);const{data,error}=await q;if(error)throw error;return data||[]}
export const SALARY_JOBS={mine:['Обычные работы','🦺 Шахта','fixed',300],courier:['Обычные работы','🛵 Курьер','orders',80,9],mail:['Обычные работы','📪 Почта','fixed',1000],taxi:['Обычные работы','🚕 Такси','taxi',180,7],bus:['Обычные работы','🚌 Автобус','bus',1600],garbage:['Обычные работы','🚮 Мусоровоз','fixed',2700],delivery:['Обычные работы','🚚 Развозчик','fixed',1400],trucker:['Обычные работы','🚛 Дальнобойщик','contract',0]};
export function calculateSalary(job,p={}){const j=SALARY_JOBS[job];if(!j)return 0;if(j[2]==='fixed')return j[3];if(j[2]==='orders')return Math.min(j[4],Math.max(0,Number(p.orders||0)))*j[3];if(j[2]==='contract')return Math.max(0,Number(p.contract_amount||0));if(j[2]==='taxi')return Math.round(Math.min(7,Math.max(0,Number(p.orders||0)))*180+({low:0,medium:300,high:600,business:1200}[p.vehicle_class]||0));if(j[2]==='bus')return Math.round(1600*({none:1,vip_interior:1.3,soundproof:1.4,climate_monitors:1.5}[p.tuning]||1));if(j[2]==='delivery')return Math.round(1400*({none:1,trunk:1.2,air_suspension:1.5}[p.tuning]||1));return 0}
export async function paySalary(id,job,p={}){const a=calculateSalary(job,p);if(a<=0)throw Error('Не удалось рассчитать зарплату');const r=await rpc('pay_salary_direct',{p_contract_amount:Number(p.contract_amount||0),p_job:job.startsWith('ess_')?'ess':job.startsWith('mvd_')?'mvd':job.startsWith('mil_')?'army':job,p_player_id:id,p_position:job.includes('_')?job.substring(job.indexOf('_')+1):null,p_tuning:{},p_units:Number(p.orders||1),p_vehicle_class:p.vehicle_class||'low'});await notice(id,'Зарплата начислена',`Вам начислена заработная плата: ${a.toLocaleString('ru-RU')} ₽. Работа: ${SALARY_JOBS[job]?.[1]||job}.`,'success');return r}
function resetModalFocus(){const a=document.activeElement;if(a&&typeof a.blur==='function')a.blur();}
export function closeAdminModal(){resetModalFocus();document.querySelectorAll('.modal').forEach(m=>{m.classList.remove('open');m.style.removeProperty('display');m.style.removeProperty('pointer-events');m.setAttribute('aria-hidden','true');m.inert=false;});document.body.classList.remove('modal-open');document.body.style.removeProperty('overflow');}
window.closeAdminModal=closeAdminModal;window.closeModal=closeAdminModal;
export function openAdminModal(id){const m=document.getElementById(id);if(!m)return false;resetModalFocus();document.querySelectorAll('.modal').forEach(x=>{x.classList.remove('open');x.style.removeProperty('display');x.style.removeProperty('pointer-events');x.setAttribute('aria-hidden','true');x.inert=true});m.inert=false;m.style.removeProperty('display');m.style.removeProperty('pointer-events');m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');document.body.style.overflow='hidden';return true}
window.openAdminModal=openAdminModal;window.openModal=openAdminModal;
// Capture phase intentionally runs before the legacy inline modal handler. It prevents that handler from restoring aria-hidden while an input/button still owns focus.
document.addEventListener('click',e=>{const close=e.target.closest('#close,.modal-close,[data-close-modal]');if(close){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();resetModalFocus();closeAdminModal();return;}if(e.target.classList.contains('modal')){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();closeAdminModal();}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAdminModal()});
function playerId(){return document.querySelector('.ops-player.active')?.dataset.id||document.querySelector('.player-row.selected')?.dataset.id||document.querySelector('[data-selected-player="true"]')?.dataset.id}
function notify(){const id=playerId();if(!id)return alert('Сначала выберите игрока');const mt=document.getElementById('mTitle'),ms=document.getElementById('mSub'),mb=document.getElementById('mBody');openAdminModal('modal');if(mt)mt.textContent='Уведомление игроку';if(ms)ms.textContent='Сообщение от банка';if(mb)mb.innerHTML='<div class="salary-grid"><label class="full">Заголовок<input id="nt" value="Сообщение банка"></label><label class="full">Текст<textarea id="nm" rows="5" style="width:100%;padding:12px;background:#091727;border:1px solid #233b57;border-radius:11px;color:#eef5ff"></textarea></label><label>Тип<select id="nk"><option value="info">Обычное</option><option value="success">Успешное</option><option value="warning">Важное</option></select></label></div><button class="primary-btn wide" id="ns" type="button">🔔 Отправить игроку</button>';const send=document.getElementById('ns');if(send)send.onclick=async()=>{try{await sendNotification(id,document.getElementById('nt')?.value,document.getElementById('nm')?.value,document.getElementById('nk')?.value);closeAdminModal();alert('Уведомление отправлено игроку')}catch(e){alert('Ошибка: '+e.message)}}}
function addNotify(){document.querySelectorAll('.right-actions,.operation-grid').forEach(x=>{if(!x.querySelector('.admin-notify')){const b=document.createElement('button');b.type='button';b.className='admin-notify action-card';b.innerHTML='<i class="fa-solid fa-bell"></i><span>Уведомление</span><small>Сообщение игроку</small>';b.addEventListener('click',notify);x.appendChild(b)}})}
if(document.body){new MutationObserver(addNotify).observe(document.body,{childList:true,subtree:true});setTimeout(addNotify,0);}
