import { supabase } from './supabase-client.js';
const money=v=>Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function me(){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Не авторизован');return user;}
export async function getMyProfile(){const user=await me();const{data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;const jd=data.job_data&&typeof data.job_data==='object'?data.job_data:{};return {...data,full_name:data.full_name||jd.full_name||jd.fio||'',passport_number:data.passport||data.passport_number||'',job_data:jd};}
export async function getMyNotifications(){const user=await me();const{data,error}=await supabase.from('bank_notifications').select('id,user_id,title,message,kind,is_read,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
export async function markNotificationRead(id){const{data,error}=await supabase.rpc('mark_bank_notification_read',{p_notification_id:Number(id)});if(error)throw error;return data;}
export async function markAllNotificationsRead(){const{data,error}=await supabase.rpc('mark_all_bank_notifications_read');if(error)throw error;return data;}
async function bankNotice(title,message,kind='info'){const user=await me();const{error}=await supabase.from('bank_notifications').insert({user_id:user.id,title,message,kind});if(error)throw error;}
export async function transferFunds(toUsername,amount){const user=await me();const{data:toUser,error:findError}=await supabase.from('profiles').select('id,username').eq('username',toUsername).single();if(findError||!toUser)throw new Error('Получатель не найден');const{error}=await supabase.rpc('transfer_funds',{p_from:user.id,p_to:toUser.id,p_amount:amount});if(error)throw error;await bankNotice('Перевод выполнен',`Вы перевели ${money(amount)} ₽ пользователю @${toUsername}.`,'success');}
export async function payFine(fineId){const user=await me();const{data:fine,error:fe}=await supabase.from('fines').select('amount,reason').eq('id',fineId).eq('user_id',user.id).single();if(fe)throw fe;const{error}=await supabase.rpc('pay_fine',{p_fine_id:fineId,p_user_id:user.id});if(error)throw error;await bankNotice('Штраф оплачен',`Вы оплатили штраф на сумму ${money(fine?.amount)} ₽. Статья: ${fine?.reason||'не указана'}.`,'success');}
export async function repayCredit(creditId,amount){const user=await me();const{data:credit,error:ce}=await supabase.from('credits').select('remaining,interest_rate').eq('id',creditId).eq('user_id',user.id).single();if(ce)throw ce;const{error}=await supabase.rpc('repay_credit',{p_credit_id:creditId,p_amount:amount,p_user_id:user.id});if(error)throw error;const left=Math.max(0,Number(credit?.remaining||0)-Number(amount));await bankNotice('Платёж по кредиту',`Вы внесли ${money(amount)} ₽. Остаток по кредиту: ${money(left)} ₽.`,'success');}
export async function getMyFines(){const user=await me();const{data,error}=await supabase.from('fines').select('*').eq('user_id',user.id).eq('is_paid',false).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getMyCredits(){const user=await me();const{data,error}=await supabase.from('credits').select('*').eq('user_id',user.id).eq('is_closed',false).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getMyTransactions(){const user=await me();const{data,error}=await supabase.from('transactions').select('*').or(`from_user.eq.${user.id},to_user.eq.${user.id}`).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
async function renderNotifications(){const c=document.getElementById('notificationList'),badge=document.getElementById('notificationBadge');if(!c)return;try{const list=await getMyNotifications();const unread=list.filter(n=>!n.is_read).length;if(badge){badge.textContent=unread?String(unread):'';badge.hidden=!unread;}if(!list.length){c.innerHTML='<div class="empty-state">📭 Сообщений от банка пока нет</div>';return;}c.innerHTML=list.map(n=>`<div class="bank-notification ${n.is_read?'read':'unread'}" data-notification="${n.id}"><div class="bank-notification-icon">${n.kind==='warning'?'⚠️':n.kind==='success'?'✅':'🔔'}</div><div class="bank-notification-body"><strong>${esc(n.title)}</strong><p>${esc(n.message)}</p><small>${new Date(n.created_at).toLocaleString('ru-RU')}</small></div>${n.is_read?'':'<button class="table-btn mark-one" type="button">Прочитать</button>'}</div>`).join('');c.querySelectorAll('.mark-one').forEach(b=>b.onclick=async()=>{try{await markNotificationRead(b.closest('[data-notification]').dataset.notification);await renderNotifications();}catch(e){alert('Ошибка: '+e.message)}});}catch(e){c.innerHTML=`<div class="empty-state">Не удалось загрузить уведомления<br><small>${esc(e.message)}</small></div>`;}}
function mountNotifications(){if(document.getElementById('bankNotifications'))return;const main=document.querySelector('.content-section');if(!main)return;const box=document.createElement('section');box.className='panel bank-notifications-panel';box.id='bankNotifications';box.innerHTML='<div class="panel-head"><div><span class="eyebrow">Центр сообщений</span><h3>🔔 Сообщения от банка <span id="notificationBadge" class="notification-badge" hidden></span></h3></div><button class="table-btn" id="readAllNotifications" type="button">Прочитать все</button></div><div id="notificationList"><div class="empty-state">Загрузка…</div></div>';main.appendChild(box);document.getElementById('readAllNotifications').onclick=async()=>{try{await markAllNotificationsRead();await renderNotifications();}catch(e){alert('Ошибка: '+e.message)}};renderNotifications();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountNotifications);else mountNotifications();
setTimeout(()=>{try{supabase.channel('bank-notifications-player-v3').on('postgres_changes',{event:'*',schema:'public',table:'bank_notifications'},()=>renderNotifications()).subscribe();}catch(e){}},500);
