import { supabase } from './supabase-client.js';
const money=v=>Number(v||0).toLocaleString('ru-RU',{minimumFractionDigits:0,maximumFractionDigits:2});
async function me(){const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Не авторизован');return user;}
export async function getMyProfile(){const user=await me();const{data,error}=await supabase.from('profiles').select('*').eq('id',user.id).single();if(error)throw error;return data;}
export async function getMyNotifications(){const user=await me();const{data,error}=await supabase.from('bank_notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
export async function markNotificationRead(id){const{error}=await supabase.from('bank_notifications').update({is_read:true}).eq('id',id);if(error)throw error;}
export async function markAllNotificationsRead(){const user=await me();const{error}=await supabase.from('bank_notifications').update({is_read:true}).eq('user_id',user.id).eq('is_read',false);if(error)throw error;}
async function bankNotice(title,message,kind='info'){const user=await me();const{error}=await supabase.from('bank_notifications').insert({user_id:user.id,title,message,kind});if(error)throw error;}
export async function transferFunds(toUsername,amount){const user=await me();const{data:toUser,error:findError}=await supabase.from('profiles').select('id,username').eq('username',toUsername).single();if(findError||!toUser)throw new Error('Получатель не найден');const{error}=await supabase.rpc('transfer_funds',{p_from:user.id,p_to:toUser.id,p_amount:amount});if(error)throw error;await supabase.from('bank_notifications').insert({user_id:toUser.id,title:'Перевод получен',message:`Вам поступил перевод на сумму ${money(amount)} ₽.`,kind:'success'});await bankNotice('Перевод выполнен',`Вы перевели ${money(amount)} ₽ пользователю @${toUsername}.`,'success');}
export async function payFine(fineId){const user=await me();const{data:fine}=await supabase.from('fines').select('amount,reason').eq('id',fineId).eq('user_id',user.id).single();const{error}=await supabase.rpc('pay_fine',{p_fine_id:fineId,p_user_id:user.id});if(error)throw error;await bankNotice('Штраф оплачен',`Вы оплатили штраф на сумму ${money(fine?.amount)} ₽. ${fine?.reason||''}`,'success');}
export async function repayCredit(creditId,amount){const user=await me();const{data:credit}=await supabase.from('credits').select('remaining,interest_rate').eq('id',creditId).eq('user_id',user.id).single();const{error}=await supabase.rpc('repay_credit',{p_credit_id:creditId,p_amount:amount,p_user_id:user.id});if(error)throw error;await bankNotice('Платёж по кредиту',`Вы внесли ${money(amount)} ₽ в погашение кредита. Остаток: ${money(Math.max(0,Number(credit?.remaining||0)-Number(amount)))} ₽.`,'success');}
export async function getMyFines(){const user=await me();const{data,error}=await supabase.from('fines').select('*').eq('user_id',user.id).eq('is_paid',false).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getMyCredits(){const user=await me();const{data,error}=await supabase.from('credits').select('*').eq('user_id',user.id).eq('is_closed',false).order('created_at',{ascending:false});if(error)throw error;return data||[];}
export async function getMyTransactions(){const user=await me();const{data,error}=await supabase.from('transactions').select('*').or(`from_user.eq.${user.id},to_user.eq.${user.id}`).order('created_at',{ascending:false}).limit(100);if(error)throw error;return data||[];}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
async function renderNotifications(){const c=document.getElementById('notificationList');if(!c)return;try{const list=await getMyNotifications();if(!list.length){c.innerHTML='<div class="empty-state">📭 Сообщений от банка пока нет</div>';return;}c.innerHTML=list.map(n=>`<div class="attention-item" data-notification="${n.id}" style="margin-bottom:8px;display:flex;gap:12px;align-items:flex-start;${n.is_read?'opacity:.72':''}"><i class="fa-solid ${n.kind==='warning'?'fa-triangle-exclamation':n.kind==='success'?'fa-circle-check':'fa-bell'}"></i><div style="flex:1"><strong>${esc(n.title)}</strong><span style="display:block;margin-top:4px;line-height:1.45">${esc(n.message)}</span><small style="display:block;margin-top:6px;opacity:.65">${new Date(n.created_at).toLocaleString('ru-RU')}</small></div>${n.is_read?'':'<button class="table-btn mark-one">Прочитано</button>'}</div>`).join('');c.querySelectorAll('.mark-one').forEach(b=>b.onclick=async()=>{await markNotificationRead(b.closest('[data-notification]').dataset.notification);await renderNotifications();});}catch(e){c.innerHTML='<div class="empty-state">Не удалось загрузить уведомления</div>';}}
function mountNotifications(){if(document.getElementById('bankNotifications'))return;const anchor=document.querySelector('.dashboard-grid')||document.querySelector('.content-section');if(!anchor)return;const box=document.createElement('article');box.className='panel';box.id='bankNotifications';box.style.cssText='margin-top:18px;grid-column:1/-1';box.innerHTML='<div class="panel-head"><div><span class="eyebrow">Банк</span><h3>🔔 Уведомления</h3></div><button class="table-btn" id="readAllNotifications">Прочитать все</button></div><div id="notificationList"><div class="empty-state">Загрузка…</div></div>';anchor.parentNode.insertBefore(box,anchor.nextSibling);document.getElementById('readAllNotifications').onclick=async()=>{await markAllNotificationsRead();await renderNotifications();};renderNotifications();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountNotifications);else mountNotifications();
setTimeout(()=>{try{supabase.channel('bank-notifications-player').on('postgres_changes',{event:'*',schema:'public',table:'bank_notifications'},()=>renderNotifications()).subscribe();}catch(e){}},500);
