-- STABILITY BANK 3.0 FINAL FEATURES
-- Notifications, per-entry history deletion, full player history deletion and profile editing.

create table if not exists public.bank_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  kind text not null default 'info',
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists bank_notifications_user_idx on public.bank_notifications(user_id, created_at desc);
alter table public.bank_notifications enable row level security;
drop policy if exists "players read own bank notifications" on public.bank_notifications;
create policy "players read own bank notifications" on public.bank_notifications for select to authenticated using (user_id=auth.uid());

create or replace function public.admin_delete_transaction(p_transaction_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
  delete from public.transactions where id::text=p_transaction_id;
  if not found then raise exception 'Операция не найдена'; end if;
  return jsonb_build_object('success',true,'deleted_id',p_transaction_id);
end;$$;
grant execute on function public.admin_delete_transaction(text) to authenticated;

create or replace function public.admin_clear_player_history(p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare n integer;
begin
  if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
  delete from public.transactions where from_user=p_player_id or to_user=p_player_id;
  get diagnostics n=row_count;
  return jsonb_build_object('success',true,'deleted_count',n);
end;$$;
grant execute on function public.admin_clear_player_history(uuid) to authenticated;

create or replace function public.admin_update_player_profile(p_player_id uuid,p_full_name text,p_birth_date date,p_passport_number text,p_username text)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
  update public.profiles set full_name=coalesce(nullif(trim(p_full_name),''),full_name),birth_date=p_birth_date,passport_number=coalesce(nullif(trim(p_passport_number),''),passport_number),username=coalesce(nullif(trim(p_username),''),username) where id=p_player_id;
  if not found then raise exception 'Игрок не найден'; end if;
  return jsonb_build_object('success',true,'player_id',p_player_id);
end;$$;
grant execute on function public.admin_update_player_profile(uuid,text,date,text,text) to authenticated;

create or replace function public.bank_create_notification(p_user_id uuid,p_title text,p_message text,p_kind text default 'info')
returns jsonb language plpgsql security definer set search_path=public as $$
declare n bigint;
begin
  if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
  insert into public.bank_notifications(user_id,title,message,kind) values(p_user_id,coalesce(nullif(trim(p_title),''),'Уведомление'),coalesce(nullif(trim(p_message),''),'Без текста'),coalesce(nullif(trim(p_kind),''),'info')) returning id into n;
  return jsonb_build_object('success',true,'id',n);
end;$$;
grant execute on function public.bank_create_notification(uuid,text,text,text) to authenticated;

create or replace function public.admin_mark_notification_read(p_notification_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
  update public.bank_notifications set is_read=true where id=p_notification_id and user_id=auth.uid();
  return jsonb_build_object('success',true);
end;$$;
grant execute on function public.admin_mark_notification_read(bigint) to authenticated;

notify pgrst,'reload schema';