-- Bank-stability 3.0 — серверная система выдачи зарплаты.
-- Зарплата НЕ хранится в банковском профиле и не зависит от поля job.

create table if not exists public.salary_rates (
  job_key text primary key,
  title text not null,
  category text not null default 'regular',
  base_amount numeric(14,2) not null default 0,
  unit_label text,
  per_unit numeric(14,2) not null default 0,
  max_units integer not null default 1,
  enabled boolean not null default true
);

insert into public.salary_rates(job_key,title,category,base_amount,unit_label,per_unit,max_units) values
 ('mine','Шахта','regular',500,null,0,1),
 ('courier','Курьер','regular',0,'за заказ',80,9),
 ('mail','Почта','regular',0,'за заказ',110,9),
 ('taxi','Такси','regular',0,'за клиента',180,7),
 ('bus','Автобус','regular',650,null,0,1),
 ('garbage','Мусоровоз','regular',750,null,0,1),
 ('delivery','Развозчик','regular',900,null,0,1),
 ('trucker','Дальнобойщик','regular',1200,null,0,1),
 ('ess','ЕСС','government',1800,null,0,1),
 ('mvd','МВД','government',2200,null,0,1)
on conflict (job_key) do update set
 title=excluded.title, category=excluded.category, base_amount=excluded.base_amount,
 unit_label=excluded.unit_label, per_unit=excluded.per_unit, max_units=excluded.max_units,
 enabled=true;

create table if not exists public.salary_payments (
  id bigint generated by default as identity primary key,
  player_id uuid not null references auth.users(id) on delete cascade,
  admin_id uuid not null references auth.users(id),
  job_key text not null,
  job_title text not null,
  amount numeric(14,2) not null check (amount > 0),
  units integer not null default 1,
  params jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists salary_payments_player_idx on public.salary_payments(player_id, created_at desc);
create index if not exists salary_payments_created_idx on public.salary_payments(created_at desc);

alter table public.salary_rates enable row level security;
alter table public.salary_payments enable row level security;

drop policy if exists salary_rates_admin_read on public.salary_rates;
create policy salary_rates_admin_read on public.salary_rates
for select to authenticated using (public.is_bank_admin());

drop policy if exists salary_payments_admin_read on public.salary_payments;
create policy salary_payments_admin_read on public.salary_payments
for select to authenticated using (public.is_bank_admin());

create or replace function public.pay_salary_direct(
  p_user_id uuid,
  p_job text,
  p_params jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.salary_rates%rowtype;
  p public.profiles%rowtype;
  v_units integer := greatest(1, coalesce((p_params->>'orders')::integer, 1));
  v_amount numeric(14,2);
  v_contract numeric(14,2) := greatest(0, coalesce((p_params->>'contract_amount')::numeric, 0));
  v_old_balance numeric(14,2);
  v_new_balance numeric(14,2);
  v_payment_id bigint;
begin
  if not public.is_bank_admin() then
    raise exception 'Недостаточно прав: зарплату может выдавать только администратор';
  end if;

  if p_user_id is null or p_job is null or btrim(p_job) = '' then
    raise exception 'Игрок и работа обязательны';
  end if;

  select * into r from public.salary_rates where job_key = lower(btrim(p_job)) and enabled = true;
  if not found then raise exception 'Неизвестная или отключённая работа: %', p_job; end if;

  select * into p from public.profiles where id = p_user_id for update;
  if not found then raise exception 'Игрок не найден'; end if;
  if coalesce(p.status,'active') <> 'active' then
    raise exception 'Нельзя выдать зарплату: аккаунт игрока имеет статус %', p.status;
  end if;

  if r.per_unit > 0 then
    v_units := least(v_units, greatest(1,r.max_units));
    v_amount := r.base_amount + r.per_unit * v_units;
  elsif r.job_key = 'custom' then
    v_amount := v_contract;
  else
    v_units := 1;
    v_amount := r.base_amount;
  end if;

  -- Дополнительные коэффициенты из параметров разрешены только как серверно ограниченный multiplier.
  if coalesce((p_params->>'multiplier')::numeric,1) < 0.5 or coalesce((p_params->>'multiplier')::numeric,1) > 2 then
    raise exception 'Недопустимый коэффициент зарплаты';
  end if;
  v_amount := round(v_amount * coalesce((p_params->>'multiplier')::numeric,1), 2);

  if v_amount <= 0 then raise exception 'Сумма зарплаты должна быть больше нуля'; end if;

  v_old_balance := coalesce(p.balance,0);
  v_new_balance := v_old_balance + v_amount;

  update public.profiles set balance = v_new_balance where id = p_user_id;

  insert into public.salary_payments(player_id,admin_id,job_key,job_title,amount,units,params)
  values(p_user_id,auth.uid(),r.job_key,r.title,v_amount,v_units,p_params)
  returning id into v_payment_id;

  insert into public.transactions(from_user,to_user,amount,type,description)
  values(null,p_user_id,v_amount,'salary','Зарплата: ' || r.title || ' (#' || v_payment_id || ')');

  return jsonb_build_object(
    'payment_id',v_payment_id,
    'player_id',p_user_id,
    'job',r.job_key,
    'title',r.title,
    'amount',v_amount,
    'units',v_units,
    'old_balance',v_old_balance,
    'new_balance',v_new_balance
  );
end;
$$;

revoke all on function public.pay_salary_direct(uuid,text,jsonb) from public;
grant execute on function public.pay_salary_direct(uuid,text,jsonb) to authenticated;
