-- BANK-STABILITY 3.0 FINAL SERVER LAYER
-- Apply this migration ONCE in Supabase SQL Editor.
-- It unifies admin finance, salary, fines, credits, transfers and player payments.

create or replace function public.is_bank_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and lower(coalesce(role,'')) = 'admin'
  );
$$;
grant execute on function public.is_bank_admin() to authenticated;

-- Salary configuration
create table if not exists public.salary_rates (
  job_key text primary key,
  title text not null,
  category text not null default 'regular',
  base_amount numeric(14,2) not null default 0,
  unit_label text,
  per_unit numeric(14,2) not null default 0,
  max_units integer not null default 1,
  enabled boolean not null default true
);

insert into public.salary_rates(job_key,title,category,base_amount,unit_label,per_unit,max_units) values
('mine','Шахта','regular',300,null,0,1),
('courier','Курьер','regular',0,'заказ',80,9),
('mail','Почта','regular',1000,null,0,1),
('taxi','Такси','regular',0,'заказ',180,7),
('bus','Автобус','regular',1600,null,0,1),
('garbage','Мусоровоз','regular',2700,null,0,1),
('delivery','Развозчик','regular',1400,null,0,1),
('trucker','Дальнобойщик','regular',0,'контракт',0,1),
('ess','ЕСС','government',0,null,0,1),
('mvd','МВД','government',0,null,0,1),
('army','Воинская часть','government',0,null,0,1)
on conflict(job_key) do update set title=excluded.title,category=excluded.category,base_amount=excluded.base_amount,unit_label=excluded.unit_label,per_unit=excluded.per_unit,max_units=excluded.max_units,enabled=true;

create table if not exists public.salary_positions (
  job_key text not null,
  position_key text not null,
  title text not null,
  salary numeric(14,2) not null check(salary >= 0),
  primary key(job_key,position_key)
);
insert into public.salary_positions(job_key,position_key,title,salary) values
('ess','driver','Водитель',1500),('ess','firefighter','Пожарный',1800),('ess','rescuer','Спасатель',2200),('ess','inspector','Инспектор',2500),('ess','paramedic','Фельдшер',2800),('ess','doctor','Врач',3200),('ess','narcologist','Нарколог',3600),('ess','surgeon','Хирург',4000),
('mvd','private','Рядовой',1500),('mvd','junior_sergeant','Мл. сержант',1800),('mvd','sergeant','Сержант',2100),('mvd','foreman','Старшина',2400),('mvd','warrant_officer','Прапорщик',2700),('mvd','junior_lieutenant','Мл. лейтенант',3000),('mvd','lieutenant','Лейтенант',3300),('mvd','captain','Капитан',3600),('mvd','major','Майор',3900),('mvd','lieutenant_colonel','Подполковник',4200),
('army','private','Рядовой',500),('army','corporal','Ефрейтор',800),('army','junior_sergeant','Мл. сержант',1100),('army','sergeant','Сержант',2000),('army','senior_sergeant','Ст. сержант',2300),('army','foreman','Старшина',2600),('army','warrant','Прапорщик',2900),('army','junior_lieutenant','Мл. лейтенант',3200),('army','lieutenant','Лейтенант',3500)
on conflict(job_key,position_key) do update set title=excluded.title,salary=excluded.salary;

create table if not exists public.salary_payments (
 id bigint generated by default as identity primary key,
 player_id uuid not null references auth.users(id) on delete cascade,
 admin_id uuid not null references auth.users(id),
 job_key text not null, job_title text not null,
 amount numeric(14,2) not null check(amount>0), units integer not null default 1,
 params jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

-- Remove the old 3-argument salary endpoint so PostgREST has one canonical RPC.
drop function if exists public.pay_salary_direct(uuid,text,jsonb);
drop function if exists public.pay_salary_direct(numeric,text,uuid,text,jsonb,integer,text);

create or replace function public.pay_salary_direct(
 p_contract_amount numeric,
 p_job text,
 p_player_id uuid,
 p_position text,
 p_tuning jsonb,
 p_units integer,
 p_vehicle_class text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
 r public.salary_rates%rowtype; pos public.salary_positions%rowtype; p public.profiles%rowtype;
 v_job text:=lower(trim(p_job)); v_amount numeric(14,2):=0; v_units integer:=greatest(0,coalesce(p_units,0));
 v_class numeric:=case lower(coalesce(p_vehicle_class,'')) when 'low' then 0 when 'medium' then 300 when 'high' then 600 when 'business' then 1200 else 0 end;
 v_mult numeric:=1; v_old numeric; v_payment bigint;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if p_player_id is null then raise exception 'Игрок не выбран'; end if;
 select * into p from public.profiles where id=p_player_id for update;
 if not found then raise exception 'Игрок не найден'; end if;
 if lower(coalesce(p.status,'active')) <> 'active' then raise exception 'Игрок не активен'; end if;
 if v_job='main' then v_job='mine'; end if;
 select * into r from public.salary_rates where job_key=v_job and enabled;
 if not found then raise exception 'Неизвестная работа %',p_job; end if;
 if v_job in ('ess','mvd','army') then
   select * into pos from public.salary_positions where job_key=v_job and position_key=p_position;
   if not found then raise exception 'Выберите должность'; end if;
   v_amount:=pos.salary;
 elsif v_job='mine' then v_amount:=300;
 elsif v_job='courier' then
   if v_units<0 or v_units>9 then raise exception 'Курьер: от 0 до 9 заказов'; end if;
   v_amount:=v_units*80;
 elsif v_job='mail' then v_amount:=1000;
 elsif v_job='taxi' then
   if v_units<0 or v_units>7 then raise exception 'Такси: от 0 до 7 заказов'; end if;
   v_amount:=v_units*180+v_class;
   if coalesce((p_tuning->>'subwoofer')::boolean,false) then v_mult:=v_mult*1.2; end if;
   if coalesce((p_tuning->>'tint1')::boolean,false) then v_mult:=v_mult*1.3; end if;
   if coalesce((p_tuning->>'tint2')::boolean,false) then v_mult:=v_mult*1.4; end if;
 elsif v_job='bus' then
   v_amount:=1600;
   if coalesce((p_tuning->>'vip_interior')::boolean,false) then v_mult:=1.3; elsif coalesce((p_tuning->>'soundproof')::boolean,false) then v_mult:=1.4; elsif coalesce((p_tuning->>'climate_monitors')::boolean,false) then v_mult:=1.5; end if;
 elsif v_job='garbage' then v_amount:=2700;
 elsif v_job='delivery' then
   v_amount:=1400;
   if coalesce((p_tuning->>'trunk')::boolean,false) then v_mult:=1.2; elsif coalesce((p_tuning->>'air_suspension')::boolean,false) then v_mult:=1.5; end if;
 elsif v_job='trucker' then
   if coalesce(p_contract_amount,0)<0 then raise exception 'Сумма контракта не может быть отрицательной'; end if;
   v_amount:=coalesce(p_contract_amount,0);
 else raise exception 'Неизвестная работа %',p_job;
 end if;
 v_amount:=round(v_amount*v_mult,2);
 if v_amount<=0 then raise exception 'Сумма зарплаты должна быть больше нуля'; end if;
 v_old:=coalesce(p.balance,0);
 update public.profiles set balance=v_old+v_amount where id=p_player_id;
 insert into public.salary_payments(player_id,admin_id,job_key,job_title,amount,units,params) values(p_player_id,auth.uid(),v_job,r.title,v_amount,greatest(1,v_units),coalesce(p_tuning,'{}'::jsonb)||jsonb_build_object('vehicle_class',p_vehicle_class,'position',p_position,'contract_amount',p_contract_amount)) returning id into v_payment;
 insert into public.transactions(from_user,to_user,amount,type,description) values(auth.uid(),p_player_id,v_amount,'salary','Зарплата: '||r.title||' #'||v_payment);
 return jsonb_build_object('success',true,'payment_id',v_payment,'amount',v_amount,'job',v_job,'old_balance',v_old,'new_balance',v_old+v_amount);
end;$$;
grant execute on function public.pay_salary_direct(numeric,text,uuid,text,jsonb,integer,text) to authenticated;

-- Unified admin balance operation. Positive = deposit, negative = withdrawal.
create or replace function public.admin_balance_operation(p_amount numeric,p_description text,p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p public.profiles%rowtype; old numeric; new numeric; a numeric:=coalesce(p_amount,0);
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if a=0 then raise exception 'Сумма не может быть нулевой'; end if;
 select * into p from public.profiles where id=p_player_id for update;
 if not found then raise exception 'Игрок не найден'; end if;
 if lower(coalesce(p.status,'active'))<>'active' then raise exception 'Игрок не активен'; end if;
 old:=coalesce(p.balance,0); new:=old+a;
 if new<0 then raise exception 'Недостаточно средств у игрока'; end if;
 update public.profiles set balance=new where id=p_player_id;
 insert into public.transactions(from_user,to_user,amount,type,description) values(case when a<0 then p_player_id else auth.uid() end,case when a>0 then p_player_id else auth.uid() end,abs(a),case when a>0 then 'deposit' else 'withdraw' end,coalesce(nullif(trim(p_description),''),'Административная операция'));
 return jsonb_build_object('success',true,'amount',a,'old_balance',old,'new_balance',new);
end;$$;
grant execute on function public.admin_balance_operation(numeric,text,uuid) to authenticated;

-- Fine issue / cancellation.
create or replace function public.admin_issue_penalty(p_amount numeric,p_player_id uuid,p_reason text,p_title text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare fid bigint;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'Сумма штрафа должна быть больше нуля'; end if;
 if not exists(select 1 from public.profiles where id=p_player_id and lower(coalesce(status,'active'))='active') then raise exception 'Игрок не найден или не активен'; end if;
 insert into public.fines(user_id,amount,reason,title,is_paid,created_at) values(p_player_id,p_amount,coalesce(p_reason,''),coalesce(nullif(p_title,''),'Штраф'),false,now()) returning id into fid;
 return jsonb_build_object('success',true,'fine_id',fid);
end;$$;
grant execute on function public.admin_issue_penalty(numeric,uuid,text,text) to authenticated;

create or replace function public.cancel_fine(p_fine_id bigint,p_admin_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare f public.fines%rowtype;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 select * into f from public.fines where id=p_fine_id for update;
 if not found then raise exception 'Штраф не найден'; end if;
 if f.is_paid then raise exception 'Оплаченный штраф нельзя отменить'; end if;
 update public.fines set is_paid=true where id=p_fine_id;
 insert into public.transactions(from_user,to_user,amount,type,description) values(auth.uid(),f.user_id,f.amount,'fine_cancel','Отмена штрафа #'||p_fine_id);
 return jsonb_build_object('success',true,'fine_id',p_fine_id);
end;$$;
grant execute on function public.cancel_fine(bigint,uuid) to authenticated;

-- Credit issue. The existing credits table is kept; only standard columns are used.
create or replace function public.issue_credit(p_user_id uuid,p_amount numeric,p_interest numeric default 0)
returns jsonb language plpgsql security definer set search_path=public as $$
declare cid bigint;
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'Сумма кредита должна быть больше нуля'; end if;
 if not exists(select 1 from public.profiles where id=p_user_id and lower(coalesce(status,'active'))='active') then raise exception 'Игрок не найден или не активен'; end if;
 insert into public.credits(user_id,amount,remaining,interest_rate,is_closed,created_at) values(p_user_id,p_amount,p_amount,coalesce(p_interest,0),false,now()) returning id into cid;
 update public.profiles set balance=coalesce(balance,0)+p_amount where id=p_user_id;
 insert into public.transactions(from_user,to_user,amount,type,description) values(auth.uid(),p_user_id,p_amount,'credit','Выдача кредита #'||cid);
 return jsonb_build_object('success',true,'credit_id',cid,'amount',p_amount);
end;$$;
grant execute on function public.issue_credit(uuid,numeric,numeric) to authenticated;

-- Player payments.
create or replace function public.pay_fine(p_fine_id bigint,p_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare f public.fines%rowtype; p public.profiles%rowtype;
begin
 if auth.uid() is distinct from p_user_id then raise exception 'Недостаточно прав'; end if;
 select * into f from public.fines where id=p_fine_id and user_id=p_user_id for update;
 if not found then raise exception 'Штраф не найден'; end if;
 if f.is_paid then raise exception 'Штраф уже оплачен'; end if;
 select * into p from public.profiles where id=p_user_id for update;
 if coalesce(p.balance,0)<f.amount then raise exception 'Недостаточно средств'; end if;
 update public.profiles set balance=coalesce(balance,0)-f.amount where id=p_user_id;
 update public.fines set is_paid=true where id=p_fine_id;
 insert into public.transactions(from_user,to_user,amount,type,description) values(p_user_id,null,f.amount,'fine_payment','Оплата штрафа #'||p_fine_id);
 return jsonb_build_object('success',true,'amount',f.amount);
end;$$;
grant execute on function public.pay_fine(bigint,uuid) to authenticated;

create or replace function public.repay_credit(p_credit_id bigint,p_amount numeric,p_user_id uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c public.credits%rowtype; p public.profiles%rowtype; a numeric;
begin
 if auth.uid() is distinct from p_user_id then raise exception 'Недостаточно прав'; end if;
 if coalesce(p_amount,0)<=0 then raise exception 'Сумма должна быть больше нуля'; end if;
 select * into c from public.credits where id=p_credit_id and user_id=p_user_id for update;
 if not found then raise exception 'Кредит не найден'; end if;
 if c.is_closed then raise exception 'Кредит уже закрыт'; end if;
 a:=least(p_amount,coalesce(c.remaining,c.amount));
 select * into p from public.profiles where id=p_user_id for update;
 if coalesce(p.balance,0)<a then raise exception 'Недостаточно средств'; end if;
 update public.profiles set balance=coalesce(balance,0)-a where id=p_user_id;
 update public.credits set remaining=greatest(0,coalesce(c.remaining,c.amount)-a),is_closed=(coalesce(c.remaining,c.amount)-a)<=0 where id=p_credit_id;
 insert into public.transactions(from_user,to_user,amount,type,description) values(p_user_id,null,a,'credit_payment','Погашение кредита #'||p_credit_id);
 return jsonb_build_object('success',true,'amount',a);
end;$$;
grant execute on function public.repay_credit(bigint,numeric,uuid) to authenticated;

-- Player-to-player transfer. Server checks status and balance.
create or replace function public.transfer_funds(p_from uuid,p_to uuid,p_amount numeric)
returns jsonb language plpgsql security definer set search_path=public as $$
declare pf public.profiles%rowtype; pt public.profiles%rowtype; a numeric;
begin
 if auth.uid() is distinct from p_from then raise exception 'Недостаточно прав'; end if;
 if p_from=p_to then raise exception 'Нельзя переводить самому себе'; end if;
 a:=coalesce(p_amount,0); if a<=0 then raise exception 'Сумма должна быть больше нуля'; end if;
 select * into pf from public.profiles where id=p_from for update;
 select * into pt from public.profiles where id=p_to for update;
 if not found then raise exception 'Получатель не найден'; end if;
 if lower(coalesce(pf.status,'active'))<>'active' or lower(coalesce(pt.status,'active'))<>'active' then raise exception 'Перевод доступен только активным игрокам'; end if;
 if coalesce(pf.balance,0)<a then raise exception 'Недостаточно средств'; end if;
 update public.profiles set balance=coalesce(balance,0)-a where id=p_from;
 update public.profiles set balance=coalesce(balance,0)+a where id=p_to;
 insert into public.transactions(from_user,to_user,amount,type,description) values(p_from,p_to,a,'transfer','Перевод игроку');
 return jsonb_build_object('success',true,'amount',a);
end;$$;
grant execute on function public.transfer_funds(uuid,uuid,numeric) to authenticated;

-- Account status controls.
create or replace function public.admin_set_player_status(p_player_id uuid,p_status text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare s text:=lower(trim(p_status));
begin
 if not public.is_bank_admin() then raise exception 'Недостаточно прав'; end if;
 if s not in ('active','frozen','blocked') then raise exception 'Недопустимый статус'; end if;
 update public.profiles set status=s where id=p_player_id;
 if not found then raise exception 'Игрок не найден'; end if;
 return jsonb_build_object('success',true,'status',s);
end;$$;
grant execute on function public.admin_set_player_status(uuid,text) to authenticated;

-- RLS stays enabled; SECURITY DEFINER functions are the only mutation path.
notify pgrst,'reload schema';
